name: loribudget
description: LoriBudget - Personal finance tracker (prototype)
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  fl_chart: ^0.60.0
  intl: ^0.18.1
  excel: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
